Main rerank
Trusted-AI/AIF360 pull request #461
Opened 2023-09-08 10:42 UTC by andrewklayk

We've implemented a set of post-processing algorithms for dealing with fairness in rankings, as described in https://arxiv.org/abs/1905.01989 (KDD 2019), complete with a demo notebook and tests.
Along with the algorithms, we've added two useful metrics for evaluating rankings that were introduced or referenced in the paper (Infeasibility Index and Discounted Cumulative Gain). Further details are available in the demo notebook.

closes #455

2023-10-03 18:47 UTC, hoffmansc requested changes
thanks @andrewklayk, this looks great! Other than the small comments, I think we can merge this.

I would love to include this in the `aif360.sklearn` subpackage as well. There is a slightly different API for those algorithms/metrics but it should actually be easier to use since you rely on DataFrames anyway. That can be a separate PR if you prefer or you can add it to this one.

2023-10-03 18:47 UTC, hoffmansc commented on aif360/algorithms/postprocessing/deterministic_reranking.py
Can you add a line to [`docs/source/modules/algorithms.rst`](https://github.com/Trusted-AI/AIF360/blob/master/docs/source/modules/algorithms.rst) in order to show the API documentation for this?

2023-10-03 18:47 UTC, hoffmansc commented on examples/demo_deterministic_reranking.ipynb
> +    "To initialize the DeterministicReranking class, we need to pass the **protected attribute values** of the priviliged and unprivileged groups.\n",
"privileged" is misspelled a couple places

2023-10-03 22:10 UTC, hoffmansc commented on aif360/algorithms/postprocessing/deterministic_reranking.py
> +            privileged_groups: list[dict]):
This type hint doesn't work in Python 3.8. You can change it to use `List` from `typing`. Type hints are optional for this package, though. We just require the type in the docstring

2023-10-04 12:10 UTC, andrewklayk commented on examples/demo_deterministic_reranking.ipynb
> +    "    data = data[['race', 'gender', 'lsat', 'ugpa', 'zfygpa']]\n"
That was the initial idea, but I couldn't get the `tempeh` import to work, despite having installed the `.[LawSchoolGPA]` option of the package. I've tried installing `tempeh` separately, reinstalling AIF360 manually and so on, but to no end. Without the import, neither the `LawSchoolGPADataset` nor the `fetch_lawschool_gpa` work.

2023-10-05 10:42 UTC, andrewklayk commented on examples/demo_deterministic_reranking.ipynb
> +    "    data = data[['race', 'gender', 'lsat', 'ugpa', 'zfygpa']]\n"
An update on this: it seems like the SEAPHE website is no more (domain expired), which means that neither this code nor the AIF360 functions work.

2023-10-09 18:57 UTC, hoffmansc commented on examples/demo_deterministic_reranking.ipynb
> +    "    data = data[['race', 'gender', 'lsat', 'ugpa', 'zfygpa']]\n"
that is unfortunate... I've reached out to SEAPHE and they're investigating. Let's give it a week and see if they can get the website back up.

2023-10-25 10:53 UTC, andrewklayk commented
Hello @hoffmansc
I've addressed the issues you stated, except for the usage of the SEAPHE dataset. The site is still down, and I've been unable to find a free-use dataset from a reputable source that would fit here as an example. 
In my opinion, the "toy example" in the notebook is enough to explain the API, so perhaps we should ditch the dataset part alltogether?

2023-11-10 16:20 UTC, rahulnair23 commented
Hi @hoffmansc - seems like the Law School dependency has been removed from the demo notebook. Is this good to merge?

2023-11-10 19:33 UTC, hoffmansc approved these changes

2023-11-10 19:35 UTC, merged