upgrade: deprecated if_delegate_has_method
Trusted-AI/AIF360 pull request #481
Opened 2023-09-22 20:44 UTC by AmirAflak

Closes #475

2023-09-22 20:46 UTC, gowriaddepalli commented on aif360/sklearn/postprocessing/__init__.py
> +    @available_if('postprocessor_')
Do we need to make any changes in the unit test?

2023-09-22 20:47 UTC, gowriaddepalli commented on aif360/sklearn/postprocessing/__init__.py
> +    @available_if('postprocessor_')
How do we test if this is working? Have we ran the code end to end to check if this is working?

2023-09-27 15:43 UTC, mnagired approved these changes
looks good, seems like straightforward replacement of `available_if` for any previous `if_delegate_has_method` lines.

2023-09-27 16:28 UTC, mnagired requested changes
actually, looks like all of the post-processing tests are failing with the same error:

`TypeError: 'str' object is not callable`

Could you please look into this?

2024-02-20 23:15 UTC, hoffmansc commented
closing in favor of #511

2024-02-20 23:15 UTC, closed without merging